.PHONY: test test-go test-web test-helm

test: test-go test-web test-helm

test-go:
	cd pkg && go test ./...
	cd services/api-server && go test ./...
	cd services/worker && go test ./...
	cd services/control-plane && go test ./...
	cd services/builder && go test ./...
	cd services/operator && go test ./...
	cd tests/conformance && go test ./...
	cd tests/integration && go test ./...

test-web:
	cd portal && npm run build

test-helm:
	helm template langopen ./deploy/helm >/dev/null
	helm template langopen ./deploy/helm -f ./deploy/helm/values-data-muc.yaml >/dev/null
